export const SAGA_OPTIONS_TOKEN = Symbol("SAGA_OPTIONS_TOKEN");
export const SAGA_TRANSPORT_TOKEN = Symbol("SAGA_TRANSPORT_TOKEN");
export const SAGA_PARTICIPANT_METADATA = Symbol("SAGA_PARTICIPANT_METADATA");
export const SAGA_HANDLER_METADATA = Symbol("SAGA_HANDLER_METADATA");
export const SAGA_HANDLER_OPTIONS_METADATA = Symbol(
  "SAGA_HANDLER_OPTIONS_METADATA",
);
