export const SAGA_OPTIONS_TOKEN = Symbol("SAGA_OPTIONS_TOKEN");
export const SAGA_TRANSPORT_TOKEN = Symbol("SAGA_TRANSPORT_TOKEN");
export const SAGA_PARTICIPANT_METADATA = Symbol("SAGA_PARTICIPANT_METADATA");
export const SAGA_PARTICIPANT_TOPICS_METADATA = Symbol(
  "SAGA_PARTICIPANT_TOPICS_METADATA",
);
export const SAGA_PARTICIPANT_OPTIONS_METADATA = Symbol(
  "SAGA_PARTICIPANT_OPTIONS_METADATA",
);
export const MESSAGE_HANDLER_METADATA = Symbol("MESSAGE_HANDLER_METADATA");
